### ISSUE TITLE
Making multiple forms per page feasible without JS

### ISSUE THREAD

**Issue by yoavweiss** [cameronjones/form-http-extensions#1]
I'm not sure that this issue is within the scope of this specification, but it is one that over-complicates building of complex Web pages with multiple logical data submission points. One example for this is creating a shopping cart, which have multiple `submit` input fields per product, and an overall  `submit` button at the bottom.

Apparently, this task can be achieved by either one of the following techniques:
- Splitting the page into multiple forms, handling form submission using JavaScript, and abandoning an accessible, HTML-only fallback.
- Merging the different logical forms into a large "mega-form", and have a single URL on the server side to split the form submissions into their different logical server side entities.
- Have multiple form submit to iframes embedded in the page, which incurs a performance penalty on the page's load time, and is complicated to style.

None of these solutions is ideal.

I believe that enabling the `target` attribute to target an HTML element (rather than an iframe, and in a similar way to current JavaScript frameworks) can ease the creation of multiple forms per page without requiring JavaScript for them to function.

I'm not sure if there are any particular security implications to enabling that. If so, enabling forms to target HTML elements may require the elements themselves declaring that their contents is somehow sandboxed.

Let me know what you think, and if this is the right specification for this kind of additions.

**Comment by cameronjones** [comment]
> I'm not sure that this issue is within the scope of this specification, but it is one that over-complicates building of complex Web pages with multiple logical data submission points. One example for this is creating a shopping cart, which have multiple submit input fields per product, and an overall submit button at the bottom.

That does sound quite complex, if you have an example it would be useful to look at. The two structural approaches within HTML would either be a single form shared between products, or a separate form for each product. What does the submit button at the bottom do in regard to all products? Perhaps this could also be a separate form?

> Splitting the page into multiple forms, handling form submission using JavaScript, and abandoning an accessible, HTML-only fallback.

With JavaScript anything is possible so i would regard this as a non-contender in aim of a HTML solution.

> Merging the different logical forms into a large "mega-form", and have a single URL on the server side to split the form submissions into their different logical server side entities.

Within the extension specification there is scope to apply individual form elements as query parameters, if the form is sent as POST, for example. This allows for some additional information to be sent "out-of-band" (with regard to the entity) which might make the implementation of this kind of mega-form a bit easier to digest on the server.

> Have multiple form submit to iframes embedded in the page, which incurs a performance penalty on the page's load time, and is complicated to style.

How does this impact load performance? The UI behavior i would expect on a form submit is for the containing page to remain static and the iframe to wait for the response. While possible, this kind of interaction i would expect to require some JavaScript to make any updates to the containing page. 

> I believe that enabling the target attribute to target an HTML element (rather than an iframe, and in a similar way to current JavaScript frameworks) can ease the creation of multiple forms per page without requiring JavaScript for them to function.

I'm not familiar with the JavaScript frameworks you reference, do you have an example of one and what they do when the target is an element without a content model? Also what happens if the response is something other than HTML? 

As i see it, the iframe is designed to encapsulate an entire document, including the potential of the context of a HTTP request. Targeting any HTML element is effectively the same form design as targeting iframes, but perhaps without the styling difficulties. What additional benefits are there?

**Comment by yoavweiss** [comment]
Here's a [gist](https://gist.github.com/yoavweiss/5198218) that refines what I wanted to define, and an identical [codepen](http://codepen.io/anon/pen/phAgz) as a visual aid.

In the example I chose the multiple forms approach, which means that my backend is as simple as I want it to be, but without JS, I'm forced to reload the entire page for any form submission. If I have many products (which include photos, so are larger than the ones in the example), that significantly disturbs the user in his shopping.

As I said, I've contemplated adding iframes where the current `<span class="quantity">` tags are, and setting them as the forms' targets, but the performance impact is prohibitive:
- It'd be adding 1 HTTP request per product to the initial page load
- The initial quantity indicators will take a while to load, even though the backend knows them
- Iframes are the [most expensive DOM element](http://www.stevesouders.com/blog/2009/06/03/using-iframes-sparingly/)
- The indicators style will have to be included in each iframe seperately (at least as far as I could tell)

I also tried adding data-URI content to the iframe (as it's initial `src`), but that didn't work cross-browser.

Regarding JS frameworks, I had [JQuery Form](http://www.malsup.com/jquery/form/#options-object) in mind as a framework that enables settings DOM elements as a target. I'm not sure regarding edge cases, but it seems like it is just adding the content to the DOM. I can further look into it if you think it matters.

The benefits of targeting DOM elements:
- Easier (& more performant) styling
- No performance penalty on initial page load (loading iframe content + creation of iframes)

I'm not sure what the security implications of such targeting would be, and it may require some sandboxing for these DOM elements.

**Comment by cameronjones** [comment]
> In the example I chose the multiple forms approach, which means that my backend is as simple as I want it to be, but without JS, I'm forced to reload the entire page for any form submission. If I have many products (which include photos, so are larger than the ones in the example), that significantly disturbs the user in his shopping.

Yes, without using JavaScript there will be a noticeable refresh when submitting a form. The only way to reduce this would be to apply some clever caching, but it will never eliminate the refresh.

> As I said, I've contemplated adding iframes where the current <span class="quantity"> tags are, and setting them as the forms' targets, but the performance impact is prohibitive:

The other option would be using the iframe's new srcdoc="" attribute which embedds the content within the element itself. This eliminates the performance impacts, but unfortunatly it's not implemented in browsers yet...

Perhaps you could pre-load the iframe urls? 

> Regarding JS frameworks, I had JQuery Form in mind as a framework that enables settings DOM elements as a target. I'm not sure regarding edge cases, but it seems like it is just adding the content to the DOM. I can further look into it if you think it matters.

Yeah, i think that's fine for JQuery but it's written as a toolkit which you can program around the edge cases. That can't really be implemented within HTML due to the lack of any conditional programming.

> I'm not sure what the security implications of such targeting would be, and it may require some sandboxing for these DOM elements.

The new iframe specification includes attributes for sandboxing. I think this element is target at the problem you identify, minus the easier styling of course.

**Comment by yoavweiss** [comment]
Thanks Cameron!

Actually, the `srcdoc` attribute that you mention is a standard way of replacing the data URIs in my hacky solution. I wasn't aware of that attribute.

So theoretically, the solution to my issues with the current specs is setting the target as a seamless iframe with a srcdoc attribute indicating the initial value. No need to complicate things with non-iframe targets :)

It's not yet working in any shipped browser, but it looks like it's almost there in Chrome (styling still has issues)
